### ISSUE TITLE
o is not working

### ISSUE THREAD

**Issue by esimov** [xyproto/o#7]
I have installed o using the go install command, but if I'm trying to run it using `$ o` command nothing happens. What I'm doing wrong or what I'm missing?

**Comment by xyproto** [comment]
The issue is that it waits for input on stdin. This is a bug. Thanks for reporting!

**Comment by xyproto** [comment]
It's fixed in `main` now. :+1:

**Comment by esimov** [comment]
I have updated to the latest code base, but the editor is still not showing up. I have tried also to build it directly.

**Comment by esimov** [comment]
If I'm running the project without building it I'm getting an error message that I should provide a file. So this means that the editor is not opening without a provided file? I would expect this message to show up even in the case of running the executable.

**Comment by esimov** [comment]
>  Is this the same result as you get?

Exactly. 

> Currently the editor is single-file only, 

Thanks for the clarification. Maybe this information could be specified explicitly in the README file.

**Comment by xyproto** [comment]
Sure, now it's mentioned in the README.

Out of curiosity, what type of workflow needs many files to be open in one editor, as opposed to opening many files in many instances of an editor?
